name: Build and Deploy for Development

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  deploy:
    name: Deploy Development
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
      TARGET: ${{ secrets.REMOTE_PATH }}
      EXCLUDE: "/.git/, /node_modules/, .env"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to remote server
        uses: easingthemes/ssh-deploy@main
